### PR TITLE
Fix biktorgj modem firmware generic check regression

### PR DESCRIPTION
**Pull request by SantX27**
The latest patch (#6) made a regression on the generic check used to find biktorgj's firmware,this should fix it for everyone. @ght can you test it for me on your stock firmware?

### CODE REVIEW

**Comment by kescherCode** [comment]
Ah, I see the issue.
@ght the shellcheck directives you removed will be neccessary (and thus introduced by me again while merging this PR), because quoted asterisks are not expanded.

**Comment by kescherCode** [comment]
The cause of this regression: I missed that commit 2a07a2c5d14bc2f5f86061c7942f1b0de4d122ef restored the quotes around `$device` I deliberately removed in order to allow the asterisk to expand.

**Comment by ght** [comment]
Ah, sorry, that was my bad, should have explicitly asked you to test on non-stock fw before merging.

Taking another look at the check, it could be changed into a simple `find | wc` along the lines of (with the path and pattern pulled out into a var of course):
```sh
if [[ "$(find /dev/serial/by-id -type l -regex '.*/usb-Quectel_EG25-G-if0[0-3]-port0' | wc -l)" == 4 ]]
    then exit # if `[0-3]` gave 4 matches, all links must exist
fi
```

IMHO it's cleaner and more readable since it gets rid of the nested for loops, but it's a matter of taste, so please let me know what you think; if you're ok with that approach, I'll put another PR together for testing.

I'd then also go ahead and [change `[` to `[[`, which is recommended unless backwards compatibility to `sh` is required](https://mywiki.wooledge.org/BashGuide/Practices#Bash_Tests).

**Comment by kescherCode** [comment]
@ght Yes, I see your point with find - it might be useful to put all included device patterns in the `devices` array (of which we currently have two) into this single regex dynamically instead of running find multiple times (in the "worst case" code path). The PKGBUILD would need to be changed to depend on `findutils`.

As for `[` -> `[[`, sure.

**Pull request merged**
